title: Sam's Github Pages
author: Sam Zhang
email: sam10.zhang@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Sam's Github pages descriptions
theme: minima
twitter_username: N/A # DO NOT include the @ character, or else the build will fail!
github_username: hexzha  # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
